### ISSUE TITLE
Whitepaper: A Minimal Viable Dataspace with Eclipse Dataspace Components utilizing Intel Software Guard Extensions

### ISSUE THREAD

**Issue by sergiustejarionos** [eclipse-dataspaceconnector/Publications#22]
A dataspace connector is a key part of any dataspace's infrastructure as it will be the agent to establish organizational identities, connect to dataspace-external data sources and sinks, and host the policy enforcement point for any in-dataspace operation.

Securing such a critical component of a dataspace against external attacks is essential in creating a convincing data-sovereign setup that can be hosted on-prem or in the cloud. 

In this white paper we are going to explain how an EDC deployment based on Confidential Computing principles - runtime encryption and attestation - is possible. We are going to show how Intel's Software Guard Extensions can be utilized to set up a Minimal Viable Dataspace (MVD) without fundamental changes to the code of the business logic.

**Comment by arianman** [comment]
Hi @PeterKoen-MSFT,
Any recommendation about the proper way of publishing this white-paper? 
Thanks

**Comment by PeterKoen-MSFT** [comment]
You can format the whitepaper as a .md and create a pull request in the Publications repository. There it can be reviewed and discussed. If it fits into the overall mission and architecture of EDC it will be a welcome contribution.

Alternatively you can publish it on your own website in the format of your choice and if it fits into the overal mission and architecture of EDC we can create a short .md file with a summary in the Publications repository that will point to the whitepaper.
