### ISSUE TITLE
Whitepaper: Adding more sections (files)

### ISSUE THREAD

**Issue by AScFH** [eclipse-dataspaceconnector/Publications#9]
As mentioned in also other issues different sections can be added to the whitepaper:

- how to design a dataspace
- how to participate a dataspace
-  ...
- analog to the introduction: a kind of conclusion or summary that could also include a visualization
- evtl. a reading list/ link list or  "where to find further information"

**Comment by tob921013** [comment]
Agreed. 

When it comes to the part of _**"how to participate in a datspacew to participate in a datspace"**_, we also could explain the process of becoming a member and what that implies in terms of compliance and touching points for interested parties.
